- hosts: localhost
  tasks:
    - copy: src=./sources.list dest=/etc/apt/sources.list owner=root mode=0664

    - apt_repository: repo='ppa:saiarcot895/myppa'

    - apt_repository: repo='ppa:neovim-ppa/unstable'

    - apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present
    - apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main' state=present

    - apt_key: url=https://apt.dockerproject.org/gpg state=present
    - apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main' state=present

    - apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present
    - apt_repository: repo='deb https://deb.nodesource.com/node_6.x xenial main' state=present
    - apt_repository: repo='deb-src https://deb.nodesource.com/node_6.x xenial main' state=present


    - apt: name={{item}} state=installed
      with_items:
        - build-essential
        - vim-nox
        - ruby
        - git
        - neovim
        - python-dev
        - python-pip
        - python3-dev
        - python3-pip
        - python-psycopg2
        - zsh
        - tmux
        - fonts-hack-ttf
        - mosh
        - silversearcher-ag
        - netcat
        - nginx
        - postgresql-9.5
        - nodejs
        - htop
        - make
        - build-essential
        - libssl-dev
        - zlib1g-dev
        - libbz2-dev
        - libreadline-dev
        - libsqlite3-dev
        - wget
        - curl
        - llvm
        - libncurses5-dev
        - libncursesw5-dev
        - xz-utils
        - libmysqlclient-dev
        - libpq-dev
        - apt-fast
        - docker-engine
        - qemu-kvm
        - libvirt-bin
        - openssh-server
        - dracut
        - initramfs-tools

    - user: name=javad groups=javad,adm,sudo,dip,plugdev,libvirtd,docker,sambashare,cdrom shell=/bin/zsh

    - postgresql_user: name=javad role_attr_flags=SUPERUSER
      become: yes
      become_user: postgres

    - copy: src=./.tmux.conf dest=/home/javad/.tmux.conf owner=javad mode=0664

    - git: repo=https://github.com/carlhuda/janus.git dest=/home/javad/.vim recursive=yes force=yes
      become: yes
      become_user: javad
    - command: "rake"
      become: yes
      become_user: javad
      args:
        chdir: "/home/javad/.vim"
    - copy: src=./.vimrc.before dest=/home/javad/.vimrc.before owner=javad mode=0664
    - copy: src=./.vimrc.after dest=/home/javad/.vimrc.after owner=javad mode=0664
    - file: path=/home/javad/.config/nvim state=directory mode=0755
    - file: src=/home/javad/.vimrc dest=/home/javad/.config/nvim/init.vim owner=javad state=link

    - git: repo=git://github.com/robbyrussell/oh-my-zsh.git dest=/home/javad/.oh-my-zsh
      become: yes
      become_user: javad
    - copy: src=./.zshrc dest=/home/javad/.zshrc owner=javad mode=0664

    - git: repo=https://github.com/yyuu/pyenv.git dest=/home/javad/.pyenv
      become: yes
      become_user: javad
    - git: repo=https://github.com/yyuu/pyenv-virtualenv.git dest=/home/javad/.pyenv/plugins/pyenv-virtualenv
      become: yes
      become_user: javad
    - git: repo=https://github.com/mxw/vim-jsx.git dest=/home/javad/.janus/vim-jsx/
      become: yes
      become_user: javad

    - git: repo=https://github.com/creationix/nvm.git dest=/home/javad/.nvm
      become: yes
      become_user: javad


    - copy: src=./.gitconfig dest=/home/javad/.gitconfig owner=javad mode=0664

    - get_url:
        url: https://github.com/docker/machine/releases/download/v0.8.0/docker-machine-Linux-x86_64
        dest: /usr/local/bin/docker-machine
        mode: 755
    - get_url:
        url: https://github.com/dhiltgen/docker-machine-kvm/releases/download/v0.7.0/docker-machine-driver-kvm
        dest: /usr/local/bin/docker-machine-driver-kvm
        mode: 755
    - pip: name=docker-compose

    - get_url:
        url: http://storage.googleapis.com/kubernetes-release/release/v1.3.0/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: 755
    - get_url:
        url: https://storage.googleapis.com/minikube/releases/v0.10.0/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: 755



