- hosts: localhost
  tasks:
    - copy: src=./etc/apt/sources.list dest=/etc/apt/sources.list owner=root mode=0664
      become: true

    - copy: src=./etc/udev/rules.d/javad.rules dest=/etc/udev/rules.d/javad.rules owner=root mode=0664
      become: true

    - apt_repository:
        repo: ppa:neovim-ppa/unstable
      become: true

    - apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present
      become: true
    - apt_repository: repo='deb https://deb.nodesource.com/node_7.x yakkety main' state=present
      become: true


    - apt_key: url=https://packages.microsoft.com/keys/microsoft.asc state=present
      become: true
    - apt_repository: repo='deb-src https://deb.nodesource.com/node_7.x yakkety main' state=present
      become: true

    - apt_repository: repo='deb https://packages.microsoft.com/repos/vscode stable main' state=present
      become: true

    - apt: name={{item}} state=installed
      with_items:
        - build-essential
        - vim-nox
        - ruby
        - git
        - neovim
        - zsh
        - tmux
        - mosh
        - silversearcher-ag
        - netcat
        - nodejs
        - htop
        - build-essential
        - powertop
        - fonts-hack-otf
        - redshift
        - redshift-gtk
      become: true

    - user: name=javad groups=sudo shell=/bin/zsh append=yes
      become: true
    - copy: src=./etc/sudoers.d/javad dest=/etc/sudoers.d/javad owner=root mode=0664
      become: true

    - copy: src=./home/javad/.tmux.conf dest=/home/javad/.tmux.conf owner=javad mode=0664
      become: true
      become_user: javad

    - git: repo=https://github.com/carlhuda/janus.git dest=/home/javad/.vim recursive=yes force=yes depth=1 update=no
      become: true
      become_user: javad
    - command: "rake"
      become: true
      become_user: javad
      args:
        chdir: "/home/javad/.vim"
    - copy: src=./home/javad/.vimrc.before dest=/home/javad/.vimrc.before owner=javad mode=0664
      become: true
      become_user: javad
    - copy: src=./home/javad/.vimrc.after dest=/home/javad/.vimrc.after owner=javad mode=0664
      become: true
      become_user: javad
    - file: path=/home/javad/.config/nvim state=directory mode=0755
      become: true
      become_user: javad
    - file: src=/home/javad/.vimrc dest=/home/javad/.config/nvim/init.vim owner=javad state=link
      become: true
      become_user: javad

    - git: repo=https://github.com/airblade/vim-gitgutter.git dest=/home/javad/.janus/vim-gitgutter-master
      become: true
      become_user: javad
    - git: repo=https://github.com/mxw/vim-jsx.git dest=/home/javad/.janus/vim-jsx/
      become: true
      become_user: javad

    - git: repo=git://github.com/robbyrussell/oh-my-zsh.git dest=/home/javad/.oh-my-zsh
      become: true
      become_user: javad
    - copy: src=./home/javad/.zshrc dest=/home/javad/.zshrc owner=javad mode=0664
      become: true
      become_user: javad

    - copy: src=./home/javad/.gitconfig dest=/home/javad/.gitconfig owner=javad mode=0664
      become: true
      become_user: javad

    - file: path=/home/javad/.config/nvim/colors state=directory
      become: true
      become_user: javad

    - get_url:
        url: https://raw.githubusercontent.com/tomasr/molokai/master/colors/molokai.vim
        dest: /home/javad/.config/nvim/colors/
        owner: javad
      become: true
      become_user: javad

    - systemd:
        name: redshift
        enabled: true
        state: started
        user: true
      become: true
      become_user: javad
    - systemd:
        name: redshift-gtk
        enabled: true
        state: started
        user: true
      become: true
      become_user: javad

